name: CI/CD Render con Docker

on:
  push:
    branches:
      - main

jobs:
  build-y-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Descargar código
      - name: 1. Descargar repositorio
        uses: actions/checkout@v3

      # 2. Preparar Docker
      - name: 2. Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: 3. Configurar Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login DockerHub
      - name: 4. Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build imagen (latest + versión)
      - name: 5. Construir imagen
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USER }}/fastapi_app:latest \
            -t ${{ secrets.DOCKER_USER }}/fastapi_app:v${{ github.run_number }} \
            .

      # 5. Push imagen
      - name: 6. Subir imagen
        run: |
          docker push ${{ secrets.DOCKER_USER }}/fastapi_app:latest
          docker push ${{ secrets.DOCKER_USER }}/fastapi_app:v${{ github.run_number }}

      # 6. Deploy en Render (usando versión, no latest)
      - name: 7. Deploy en Render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: ${{ secrets.DOCKER_USER }}/fastapi_app:v${{ github.run_number }}
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true