name: CI/CD Render Docker (jobs separados)

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/fastapi_app
  IMAGE_TAG: v${{ github.run_number }}

jobs:

  # =========================
  # 1. BUILD
  # =========================
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: 1. Descargar repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: 3. Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: 4. Definir tag
        id: meta
        run: |
          echo "tag=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: 5. Construir imagen
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ steps.meta.outputs.tag }} \
            .

      - name: 6. Guardar imagen como artifact
        run: |
          docker save $IMAGE_NAME:${{ steps.meta.outputs.tag }} -o image.tar

      - name: 7. Subir artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


  # =========================
  # 2. PUSH
  # =========================
  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: 2. Cargar imagen
        run: |
          docker load -i image.tar

      - name: 3. Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 4. Subir imagen
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ needs.build.outputs.image_tag }}


  # =========================
  # 3. DEPLOY
  # =========================
  deploy:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: 1. Deploy en Render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: $IMAGE_NAME:${{ needs.build.outputs.image_tag }}